### PR TITLE
Update Chinese Translations (zh_cn)

### PR DESCRIPTION
**Pull request by ChuijkYahus**
Up to date with RC-10

Hi, I'm recently working on updating the old Chinese translations, but I've met several translation bumps. So I wanna ask these names' etymologies or if the CN word choice is OK.

Everything other than ones related to the bumps is done tho.

- **Pendorite**: curr.trsl. is "潘多拉金"(_lit. Pandora metal, Pandora as in Pandora's box_), its en name is slightly different from Pandora, wish to know its etymology.
- **Rocky Stone**: curr.trsl. is "鹅卵石"(_lit. pebble_), dunno if it's OK.
- **Bulbis**: curr.trsl. is "灯状菇"(_lit. bulb-shaped fungus_), dunno if it's OK.
- **Oddity & Anomaly**: oddity's curr.trsl. is "子实体"(_lit. sporocarp_). The former trsltor probably thinks it's a kind of fungus so they chose this word. Wish to know if they're just different forms of their respective fungus and what does these names mean other than bizzareness.
- **Cika**: curr.trsl. is "锡卡"(_pure transliteration_), is its pronunciation SI-KA/'sɪka/ or CHI-KA/'tʃɪka/.
- **Imparius**: no curr.trsl., wish to know its etymology and if its connected to "impair" or "oddness", also if it lies between normal trees & Nether/Overworld giant fungi/mushrooms since it has a tree-like form & a fungal form.
- **Phylium & Phycelium**: no unified trsl., wish to know if it's an End version of nylium, and if so, is it related to "leaves", "algea" or just "fungus".
- **Arisian**: completely no clue what it is, wish to know its etymology. _tho I think wither oak is gonna be removed?_
- **Viscal**: curr.trsl. is "威斯克"(_pure transliteration_), wish to know its etymology and if it's related to "visceral".
- **Sculk**: curr.trsl. is "潜影"(_lit. shulk_), wish to know if it's the same stuff as that in 1.19.
- **Ivis**: curr.trsl. is "伊维斯"(_pure transliteration_), wish to know if it's related to "ivy" and how should one pronounce it(is it EE-VIS/'i:vɪs/ or AYE-VIS/'aɪvɪs/).
- **Embur Pedu**: curr.trsl. is "菌柄"(_the same as in Crimson Stem_), wish to know what actually does Pedu mean.
- **Thereal Bellflower**: wish to know if "Thereal" is the same as "Ethereal".

Sorry about the translation mess, and thank you for reading.

Co-authored-by: creeping-creeper <2714328217@qq.com> (BYG's mod-page main editor on mcmod.cn)
Co-authored-by: n0099 <n0099@github.com>/<n@n0099.net>
Co-authored-by: TartaricAcid <TartaricAcid@github.com>/<bakabaka943@gmail.com>

### CODE REVIEW

**Comment by CorgiTaco** [comment]
Hey could you when you get the chance ensure that any keys you deleted before bc they weren't in a given version, could you add those back? I see there's over 300 lines that were deleted without replacements on this repo. Not your fault, but now that all BYG versions are combined it shows them as missing :P

**Comment by ChuijkYahus** [comment]
Will done soon (checking them now)

**Comment by ChuijkYahus** [comment]
The translations are on the latest versions for 1.16 & 1.18
Older versions probably have a lot of different key names for the same thing, also the cn name for the same thing in vanilla may change over versions.

**Comment by ChuijkYahus** [comment]
trsls of older versions fixed

> Also may I ask again about the etymologies

**Comment by ChuijkYahus** [comment]
Now it's done & up to date with RC-10!

**Comment by ChuijkYahus** [comment]
Co-authored-by: creeping-creeper <2714328217@qq.com> (BYG's mod-page main editor on mcmod.cn)
Co-authored-by: n0099 <n0099@github.com>/<n@n0099.net>
Co-authored-by: TartaricAcid <TartaricAcid@github.com>/<bakabaka943@gmail.com>

**Comment by ChuijkYahus** [comment]
Hey sorry for not updating for a long time.
Versions up to date with 1.4 would be done soon!

**Comment by ChuijkYahus** [comment]
looks like the translation project is gonna migrate to crowdin
this pr would be closed & the translations would be posted to crowdin once ready

**Pull request closed without merging**
